name: Update
on:
  schedule:
    - cron: '26 20 * * *'  # Ahora se ejecutará todos los días a las 20:15 UTC
  workflow_dispatch:  # Esto te permite ejecutar el flujo de trabajo manualmente desde GitHub

jobs:
  update:
    name: update
    runs-on: ubuntu-latest  # Define que se ejecuta en un entorno Ubuntu

    steps:
      - name: checkout
        uses: actions/checkout@v2  # Clona el repositorio
        with:
          ref: master  # Se asegura de usar la rama 'master' (o la que prefieras)

      - name: python setup
        uses: actions/setup-python@v2  # Configura Python
        with:
          python-version: '3.12'  # Usa Python 3.12

      - name: python install
        run: |
          python -m pip install --upgrade pip  # Actualiza pip
          pip install -r update/requirements.txt  # Instala las dependencias

      - name: update data
        run: |
          python update/update.py  # Ejecuta el script de actualización (ajusta la ruta si es necesario)

      - name: commit
        run: |
          git config --global user.email "convocatorias-bot@example.com"  # Configura el correo del bot
          git config --global user.name "convocatorias-bot"  # Configura el nombre del bot
          git add -A  # Agrega todos los cambios
          git diff --quiet && git diff --staged --quiet || (git commit -m "[ci] $(date -d 'yesterday' +%Y-%m-%d)" && git push -q "https://$GH_TOKEN@github.com/BayronFdez/Fork.git" master)  # Hace commit si hay cambios
